"""
Constants pour le système RBAC (Role-Based Access Control)
"""

# ================= CONSTANTES RÔLES =================
ROLE_SUPER_ADMIN = "SUPER_ADMIN"
ROLE_PRODUCT_OWNER = "PRODUCT_OWNER"
ROLE_SCRUM_MASTER = "SCRUM_MASTER"
ROLE_DEVELOPPEUR = "DEVELOPPEUR"
ROLE_TESTEUR_QA = "TESTEUR_QA"

# Niveaux d'accès (du plus élevé au plus bas)
NIVEAU_SUPER_ADMIN = 100
NIVEAU_PRODUCT_OWNER = 80
NIVEAU_SCRUM_MASTER = 70
NIVEAU_TESTEUR_QA = 60
NIVEAU_DEVELOPPEUR = 50
