"""add ai_prompt_logs

Revision ID: f20da35f0c50
Revises: 
Create Date: 2026-03-06 02:08:14.094144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20da35f0c50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projet', 'key',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint(op.f('userstory_assigneeId_fkey'), 'userstory', type_='foreignkey')
    op.create_foreign_key(None, 'userstory', 'utilisateur', ['assigneeId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userstory', type_='foreignkey')
    op.create_foreign_key(op.f('userstory_assigneeId_fkey'), 'userstory', 'utilisateur', ['assigneeId'], ['id'], ondelete='SET NULL')
    op.alter_column('projet', 'key',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
